# Generated by Django 5.1.4 on 2025-01-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipies',
            name='ingredients',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
