# Generated by Django 5.1.4 on 2025-01-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='Type your message here'),
        ),
        migrations.AddField(
            model_name='contact',
            name='telephone',
            field=models.CharField(default='44700000000', max_length=12),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
